package com.refiq.platform.calculation.api.web;

import com.refiq.platform.calculation.api.dto.CalculationRequest;
import com.refiq.platform.calculation.api.dto.CalculationResult;
import com.refiq.platform.calculation.internal.logging.CalculationLogEvent; // Añadido el import transversal
import com.refiq.platform.calculation.internal.service.CalculationService;
import java.util.List;
import java.util.concurrent.ExecutorService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * REST Controller responsible for handling automated S3 event notifications from MinIO.
 * <p>
 * This controller acts as the entry point for the return phase of the asynchronous
 * data ingestion and calculation pipeline. It listens for object creation events in
 * the Data Lake's Gold layer and triggers the statistical calculation engine (R/Plumber)
 * to process the newly normalized clinical data.
 * </p>
 */
@RestController
@RequestMapping("/api/v1/webhooks/minio")
public class MinioWebhookController {

  private static final Logger log = LoggerFactory.getLogger(MinioWebhookController.class);
  private final CalculationService calculationService;
  private final ExecutorService webhookExecutor;

  // --- Internal DTOs to map the MinIO JSON payload ---
  public record MinioEvent(List<MinioRecord> Records) {}
  public record MinioRecord(MinioS3 s3) {}
  public record MinioS3(MinioObject object) {}
  public record MinioObject(String key) {}

  public MinioWebhookController(CalculationService calculationService,
      @Qualifier("webhookExecutor") ExecutorService webhookExecutor) {
    this.calculationService = calculationService;
    this.webhookExecutor = webhookExecutor;
  }

  /**
   * Processes incoming webhook events from MinIO triggered by S3 object modifications.
   * <p>
   * MinIO expects a rapid 2xx response to acknowledge receipt of the event. To prevent
   * blocking the webhook dispatcher, this method immediately delegates the actual calculation
   * payload to a background Virtual Thread and returns a {@code 200 OK} status. It explicitly
   * filters incoming records to only react to files landing in the designated {@code 3.Gold/} directory.
   * </p>
   *
   * @param event The JSON payload generated by MinIO containing S3 event records.
   * @return An empty HTTP 200 response to acknowledge successful receipt and parsing.
   */
  @PostMapping
  public ResponseEntity<Void> handleMinioEvent(@RequestBody MinioEvent event) {
    if (event.Records() == null || event.Records().isEmpty()) {
      return ResponseEntity.ok().build();
    }

    for (MinioRecord record : event.Records()) {
      String s3Key = record.s3().object().key();

      if (s3Key != null && s3Key.startsWith("3.Gold/")) {
        new CalculationLogEvent.MinioWebhookReceived(s3Key).log(log);

        String testCode = extractAnalyteFromKey(s3Key);

        CalculationRequest request = new CalculationRequest(s3Key, null, null, testCode);

        webhookExecutor.submit(() -> processCalculation(request));
      }
    }

    return ResponseEntity.ok().build();
  }

  /**
   * Asynchronously orchestrates the reference interval calculation for a specific clinical file.
   * <p>
   * Evaluates the outcome using Pattern Matching over the sealed {@link CalculationResult} hierarchy.
   * Since persistence is handled by the CalculationService, this controller strictly focuses on
   * logging the corresponding clinical results, data inconsistencies, or technical engine errors
   * utilizing the domain-specific logging catalog.
   * </p>
   *
   * @param request The domain request containing the S3 key and required statistical parameters.
   */
  private void processCalculation(CalculationRequest request) {
    try {
      CalculationResult result = calculationService.runAnalysis(request);

      switch (result) {
        case CalculationResult.Success s ->
            new CalculationLogEvent.CalculationSuccess(request.testCode(), s.response().labResult().referenceRange()).log(log);

        case CalculationResult.DataInconsistency di ->
            new CalculationLogEvent.CalculationDataInconsistency(request.testCode(), di.details()).log(log);

        case CalculationResult.EngineUnavailable eu ->
            new CalculationLogEvent.CalculationEngineUnavailable(request.testCode(), eu.debugInfo()).log(log);

        case CalculationResult.InvalidRequest ir ->
            new CalculationLogEvent.CalculationInvalidRequest(request.s3Key()).log(log);

        case CalculationResult.AlreadyHandled ah ->
            new CalculationLogEvent.MinioWebhookDuplicateIgnored(request.testCode(), ah.status()).log(log);
      }
    } catch (Exception e) {
      new CalculationLogEvent.MinioWebhookError(e.getMessage()).log(log);
    }
  }

  /**
   * Extracts the clinical analyte identifier from a standardized S3 Gold layer key.
   * <p>
   * Expected key format: {@code 3.Gold/{ANALYTE}/{filename}.parquet}.
   * If the structural parsing fails, it safely defaults to {@code "UNKNOWN"} to prevent breaking
   * the execution flow, relying on the underlying calculation engine to reject the invalid test code.
   * </p>
   *
   * @param key The full S3 object key (e.g., "3.Gold/TSH/TSH_gold_table.parquet").
   * @return The extracted analyte code (e.g., "TSH"), or "UNKNOWN" if parsing fails.
   */
  private String extractAnalyteFromKey(String key) {
    try {
      return key.split("/")[1];
    } catch (Exception e) {
      new CalculationLogEvent.MinioWebhookParsingWarn(key).log(log);
      return "UNKNOWN";
    }
  }
}