package com.refiq.platform.calculation.api.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/**
 * Represents the final output of the calculation engine, mapped to the MVP JSON contract.
 *
 * @param labResult  The clinical data result containing the calculated reference intervals.
 * @param parameters Technical parameters used or generated during the calculation (e.g., algorithm convergence stats).
 */
public record CalculationResponse(
    @JsonProperty("lab_result") LabResult labResult,
    Map<String, Double> parameters
) {

  /**
   * Nested record isolating clinical data from technical metadata.
   *
   * @param testCode       The identifier of the test (e.g., LOINC).
   * @param name           The human-readable name of the test.
   * @param value          The calculated central tendency value (mean/median). Can be null if the input was population-only.
   * @param unit           The unit of measurement.
   * @param referenceRange The calculated reference interval formatted as a string (e.g., "70-100").
   * @param notes          Any warnings or notes generated by the clinical algorithm.
   */
  public record LabResult(
      @JsonProperty("test_code") String testCode,
      String name,
      Double value, // Deuda quitar esto

      // Puede ser null si el CSV solo tiene población
      String unit,
      @JsonProperty("reference_range") String referenceRange, // Formato "70-100"
      String notes
  ) {

  }
}