package com.refiq.platform.calculation.api.web;


import com.refiq.platform.calculation.api.dto.CalculationRequest;
import com.refiq.platform.calculation.api.dto.CalculationResult;
import com.refiq.platform.calculation.internal.service.CalculationLogEvent;
import com.refiq.platform.calculation.internal.service.CalculationService;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;



/**
 * REST Controller responsible for handling automated S3 event notifications from MinIO.
 * <p>
 * This controller acts as the entry point for the return phase of the asynchronous
 * data ingestion and calculation pipeline. It listens for object creation events in
 * the Data Lake's Gold layer and triggers the statistical calculation engine (R/Plumber)
 * to process the newly normalized clinical data.
 * </p>
 */
@RestController
@RequestMapping("/api/v1/webhooks/minio")
@RequiredArgsConstructor
public class MinioWebhookController {

  private static final Logger log = LoggerFactory.getLogger(MinioWebhookController.class);
  private final CalculationService calculationService;

  // Usamos hilos virtuales para no bloquear la respuesta al webhook
  private final ExecutorService executor = Executors.newVirtualThreadPerTaskExecutor();

  // --- DTOs internos para mapear el JSON de MinIO ---
  public record MinioEvent(List<MinioRecord> Records) {}
  public record MinioRecord(MinioS3 s3) {}
  public record MinioS3(MinioObject object) {}
  public record MinioObject(String key) {}



  /**
   * Processes incoming webhook events from MinIO triggered by S3 object modifications.
   * <p>
   * MinIO expects a rapid 2xx response to acknowledge receipt of the event. To prevent
   * blocking the webhook dispatcher, this method immediately delegates the actual calculation
   * payload to a background Virtual Thread and returns a {@code 200 OK} status. It explicitly
   * filters incoming records to only react to files landing in the designated {@code 3.Gold/} directory.
   * </p>
   *
   * @param event The JSON payload generated by MinIO containing S3 event records.
   * @return An empty HTTP 200 response to acknowledge successful receipt and parsing.
   */
  @PostMapping
  public ResponseEntity<Void> handleMinioEvent(@RequestBody MinioEvent event) {
    if (event.Records() == null || event.Records().isEmpty()) {
      return ResponseEntity.ok().build();
    }

    for (MinioRecord record : event.Records()) {
      String s3Key = record.s3().object().key();

      // Aseguramos que solo procesamos lo que cae en la capa Gold
      if (s3Key != null && s3Key.startsWith("3.Gold/")) {
        CalculationLogEvent.MINIO_WEBHOOK_RECEIVED.log(log, s3Key);

        // Extraemos el analito de la ruta (Ej: 3.Gold/TSH/TSH_gold.parquet -> TSH)
        String testCode = extractAnalyteFromKey(s3Key);

        // Preparamos la petición para el motor R
        CalculationRequest request = new CalculationRequest(s3Key, null, null, testCode);

        // Delegamos el cálculo a un hilo virtual para liberar a MinIO rápido
        executor.submit(() -> processCalculation(request));
      }
    }

    // MinIO necesita un 2xx rápido para saber que hemos recibido el evento
    return ResponseEntity.ok().build();
  }


  /**
   * Asynchronously orchestrates the reference interval calculation for a specific clinical file.
   * <p>
   * Evaluates the outcome using Pattern Matching over the sealed {@link CalculationResult} hierarchy.
   * Since persistence is handled by the CalculationService, this controller strictly focuses on
   * logging the corresponding clinical results, data inconsistencies, or technical engine errors
   * utilizing the domain-specific logging catalog.
   * </p>
   *
   * @param request The domain request containing the S3 key and required statistical parameters.
   */
  private void processCalculation(CalculationRequest request) {
    try {
      CalculationResult result = calculationService.runAnalysis(request);

      // El servicio ya ha actualizado la BD con el JSON o el Error.
      // Este switch queda estrictamente para auditoría y trazabilidad en consola.
      switch (result) {
        case CalculationResult.Success s ->
            CalculationLogEvent.CALCULATION_SUCCESS.log(log, request.testCode(), s.response().labResult().referenceRange());

        case CalculationResult.DataInconsistency di ->
            CalculationLogEvent.CALCULATION_DATA_INCONSISTENCY.log(log, request.testCode(), di.details());

        case CalculationResult.EngineUnavailable eu ->
            CalculationLogEvent.CALCULATION_ENGINE_UNAVAILABLE.log(log, request.testCode(), eu.debugInfo());

        case CalculationResult.InvalidRequest ir ->
            CalculationLogEvent.CALCULATION_INVALID_REQUEST.log(log, ir.reason());
      }
    } catch (Exception e) {
      CalculationLogEvent.MINIO_WEBHOOK_ERROR.log(log, e.getMessage());
    }
  }


  /**
   * Extracts the clinical analyte identifier from a standardized S3 Gold layer key.
   * <p>
   * Expected key format: {@code 3.Gold/{ANALYTE}/{filename}.parquet}.
   * If the structural parsing fails, it safely defaults to {@code "UNKNOWN"} to prevent breaking
   * the execution flow, relying on the underlying calculation engine to reject the invalid test code.
   * </p>
   *
   * @param key The full S3 object key (e.g., "3.Gold/TSH/TSH_gold_table.parquet").
   * @return The extracted analyte code (e.g., "TSH"), or "UNKNOWN" if parsing fails.
   */
  private String extractAnalyteFromKey(String key) {
    try {
      // Split de "3.Gold/TSH/TSH_gold_table.parquet" -> ["3.Gold", "TSH", "TSH_gold_table.parquet"]
      return key.split("/")[1];
    } catch (Exception e) {
      CalculationLogEvent.MINIO_WEBHOOK_PARSING_WARN.log(log, key);
      return "UNKNOWN";
    }
  }

}
