version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: refiq-app
    ports:
      - "8080:8080"
    # ¡Aquí está la magia! Le decimos que chupe todas las variables del archivo .env
    env_file:
      - .env
    depends_on:
      - postgres
      - minio
      - r-engine

  postgres:
    image: postgres:15-alpine
    container_name: refiq-postgres
    ports:
      - "5432:5432"
    environment:
      # Mapeamos las variables del .env a las que necesita la imagen oficial de Postgres
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_local_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: refiq-minio-dev
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      # Mapeamos las variables del .env a las de MinIO
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_local_data:/data

  r-engine:
    build:
      context: ./src/main/java/com/refiq/engine
      dockerfile: Dockerfile
    container_name: refiq-engine
    ports:
      - "8000:8000"

volumes:
  postgres_local_data:
  minio_local_data: