package com.refiq.platform.calculation.internal.service;

import com.refiq.platform.shared.observability.Loggable;

public enum CalculationLogEvent implements Loggable {

  CALCULATION_STARTED(LogLevel.INFO,
      "Initiating range calculation for file: {} with percentiles [{}, {}]"),
  PLUMBER_REQUEST_SENT(LogLevel.DEBUG, "Sending request to Plumber for S3 key: {}"),
  CALCULATION_COMPLETED(LogLevel.INFO, "Calculation successfully completed for test: {}"),
  PLUMBER_ERROR(LogLevel.ERROR, "Error in the R engine (Plumber): {}"),
  ANALYSIS_INITIATED(LogLevel.DEBUG, "Sending request to R Plumber for S3Key: {}"),

  R_RESPONSE_RECEIVED(LogLevel.DEBUG, "Raw JSON received from R: {}"),
  R_DESERIALIZATION_ERROR(LogLevel.ERROR, "Critical error deserializing R response. JSON: {}"),
  R_TECHNICAL_ERROR(LogLevel.ERROR, "The R engine returned an HTTP error. Status: {}"),

  // --- MinIO Webhooks ---
  MINIO_WEBHOOK_RECEIVED(LogLevel.INFO, "MinIO webhook received for Gold file: {}"),
  MINIO_WEBHOOK_PARSING_WARN(LogLevel.WARN,
      "Could not extract analyte code from path: {}"),
  MINIO_WEBHOOK_ERROR(LogLevel.ERROR, "Unexpected error processing MinIO webhook: {}"),
  MINIO_WEBHOOK_DUPLICATE_IGNORED(LogLevel.INFO,
      "Duplicate webhook ignored for analyte {}. DB State: {}"),

  // --- Calculation Results Handling ---
  CALCULATION_SUCCESS(LogLevel.INFO, "Successful calculation for {}. Range: {}"),
  CALCULATION_DATA_INCONSISTENCY(LogLevel.WARN, "Data inconsistency for {}: {}"),
  CALCULATION_ENGINE_UNAVAILABLE(LogLevel.ERROR, "R engine unavailable for {}: {}"),
  CALCULATION_INVALID_REQUEST(LogLevel.ERROR, "Invalid request generated by Webhook: {}"),

  // --- Persistence ---
  CALCULATION_RESULT_SAVED(LogLevel.INFO, "Calculation successful. JSON saved in DB for fileId: {}"),

  // --- Business Inconsistencies ---
  DATA_INCONSISTENCY_TRACKED(LogLevel.WARN,
      "Data inconsistency detected and tracked [FileID: {}]. Details: {}");

  private final LogLevel level;
  private final String messageTemplate;

  CalculationLogEvent(LogLevel level, String messageTemplate) {
    this.level = level;
    this.messageTemplate = messageTemplate;
  }

  @Override
  public LogLevel getLevel() {
    return level;
  }

  @Override
  public String getMessageTemplate() {
    return messageTemplate;
  }
}